# Global settings
global:
  appName: "shopnow-discovery-server"       
  namespace: "shopnow"        
  enabledComponents:
    configmap: true          
    service: true            
    ingress: true             

# Deployment
image:
  repository: ""
  tag: "v1"
  pullPolicy: Always

replicaCount: 1
rollingUpdate:
  maxSurge: 25%
  maxUnavailable: 25%

service:
  type: ClusterIP
  port: 8761
  targetPort: 8761

ingress:
  className: "alb"
  host: "discovery-server-shopnow.tranvix.click"
  path: "/"
  pathType: Prefix
  certificateArn: ""
  subnets: ""
  listenPorts: ""
  groupName: ""
  actionsSslRedirect: ""

configmap:
  data: {}

serviceAccount:
  create: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80