apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopnow-discovery-server
  namespace: argocd
spec:
  destination:
    namespace: shopnow
    server: https://kubernetes.default.svc
  source:
    path: discovery-server/shopnow-discovery-server-chart
    repoURL: https://github.com/tranvix0910/shopnow-backend.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
        - ../shopnow-discovery-server-config/overlays/production/values.yaml
      values: |
        image:
          repository: "022499043310.dkr.ecr.ap-southeast-1.amazonaws.com/shopnow/shopnow-discovery-server"
  project: shopnow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true