ingress:
  certificateArn: "arn:aws:acm:ap-southeast-1:022499043310:certificate/506d551a-b534-4f5b-af8f-5e8cedfe0e0b"
  subnets: "subnet-0b78796b583490b19, subnet-0e57056ac64de1902, subnet-0501cacaf96e89a09"
  listenPorts: '[{"HTTP": 80}, {"HTTPS":443}]'
  groupName: "shopnow"
  actionsSslRedirect: '{"Type": "redirect", "RedirectConfig": {"Protocol": "HTTPS", "Port": "443", "Host": "#{host}", "Path": "/#{path}", "Query": "#{query}", "StatusCode": "HTTP_301"}}' 

# ConfigMap override for production environment
configmap:
  data:
    application.properties: |
      spring.application.name=cart-service
      server.port=5863

      eureka.instance.hostname=cart-service
      eureka.instance.instance-id=${spring.application.name}
      eureka.client.service-url.defaultZone=http://shopnow-discovery-server-service:8761/eureka/

      spring.datasource.url=jdbc:postgresql://postgres:5432/postgres?useSSL=false
      spring.datasource.username=postgres
      spring.datasource.password=admin
      spring.jpa.hibernate.ddl-auto=update
      spring.jpa.show-sql=true
      spring.jpa.properties.hibernate.format-sql=true