apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: shopnow-database-services
  namespace: shopnow

resources:
  - patches/keycloak-realm-configmap.yaml
  - patches/shopnow-keycloak-mysql.yaml
  - patches/shopnow-keycloak-realms.yaml
  - patches/shopnow-postgresql.yaml
  - patches/storage-patch.yaml

namespace: shopnow

images:
  - name: mysql
    newTag: "8.0"
  - name: quay.io/keycloak/keycloak
    newTag: "23.0.3"
  - name: postgres
    newTag: "15"

sortOptions:
  order: fifo
