# Global settings
global:
  appName: "shopnow-user-service"
  namespace: "shopnow"
  enabledComponents:
    configmap: true
    service: true
    ingress: true

# Deployment
image:
  repository: ""
  tag: "v1.0.0_b873ba3"
  pullPolicy: Always

replicaCount: 1
revisionHistoryLimit: 11
rollingUpdate:
  maxSurge: 25%
  maxUnavailable: 25%

# Service
service:
  type: ClusterIP
  port: 5865
  targetPort: 5865

# Ingress
ingress:
  className: "alb"
  host: "user-service-shopnow.tranvix.click"
  path: "/"
  pathType: Prefix
  certificateArn: ""
  subnets: ""
  listenPorts: ""
  groupName: ""
  actionsSslRedirect: ""

# ConfigMap
configmap:  
  data: {}

serviceAccount:
  create: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80